import { ICustomerAndAppointments } from "@/types/customers";

export const mockCustomers: ICustomerAndAppointments[] = [
  {
    id: "1",
    fullName: "John Doe",
    phone: "(+55) 98765-4321",
    age: 35,
    address: "Rua das Flores, 123, São Paulo, SP",
    photoUrl: "",
    customerType: "adulto",
    appointmentsCount: 4,
  },
  {
    id: "2",
    fullName: "Jane Smith",
    phone: "(+55) 91234-5678",
    age: 28,
    address: "Avenida Paulista, 1000, São Paulo, SP",
    photoUrl: "",
    customerType: "mirim",
    appointmentsCount: 3,
  },
  {
    id: "3",
    fullName: "Robert Johnson",
    phone: "(+55) 99876-5432",
    age: 42,
    address: "Rua Augusta, 500, São Paulo, SP",
    photoUrl: "",
    customerType: "familiar",
    appointmentsCount: 2,
  },
  {
    id: "4",
    fullName: "Emily Davis",
    phone: "(+55) 97654-3210",
    age: 31,
    address: "Rua Oscar Freire, 300, São Paulo, SP",
    photoUrl: "",
    customerType: "adulto",
    appointmentsCount: 4,
  },
  {
    id: "5",
    fullName: "Michael Wilson",
    phone: "(+55) 95555-4444",
    age: 45,
    address: "Alameda Santos, 800, São Paulo, SP",
    photoUrl: "",
    customerType: "adulto",
    appointmentsCount: 1,
  },
  {
    id: "6",
    fullName: "Sarah Brown",
    phone: "(+55) 94444-3333",
    age: 29,
    address: "Rua Haddock Lobo, 400, São Paulo, SP",
    photoUrl: "",
    customerType: "mirim",
    appointmentsCount: 2,
  },
  {
    id: "7",
    fullName: "David Miller",
    phone: "(+55) 93333-2222",
    age: 38,
    address: "Avenida Rebouças, 600, São Paulo, SP",
    photoUrl: "",
    customerType: "adulto",
    appointmentsCount: 0,
  },
  {
    id: "8",
    fullName: "Jennifer Taylor",
    phone: "(+55) 92222-1111",
    age: 33,
    address: "Rua da Consolação, 700, São Paulo, SP",
    photoUrl: "",
    customerType: "adulto",
    appointmentsCount: 1,
  },
  {
    id: "9",
    fullName: "Thomas Anderson",
    phone: "(+55) 91111-0000",
    age: 41,
    address: "Avenida Brigadeiro Faria Lima, 1500, São Paulo, SP",
    photoUrl: "",
    customerType: "familiar",
    appointmentsCount: 3,
  },
  {
    id: "10",
    fullName: "Lisa White",
    phone: "(+55) 90000-9999",
    age: 27,
    address: "Rua Bela Cintra, 300, São Paulo, SP",
    photoUrl: "",
    customerType: "mirim",
    appointmentsCount: 2,
  },
];
