export const MockAppointmentsData = [
  {
    id: "1",
    customerName: "John Doe",
    customerId: "1",
    age: 35,
    phone: "(+55) 98765-4321",
    dateTime: new Date("2025-06-15T10:30:00"),
    status: "confirmado",
    customerType: "adulto",
    professional: "Dra. Ana Silva",
    serviceType: "Preventivo para mulher",
    notes: "Paciente com histórico de hipertensão. Verificar medicação atual.",
  },
  {
    id: "2",
    customerName: "Jane Smith",
    customerId: "2",
    age: 28,
    phone: "(+55) 91234-5678",
    dateTime: new Date("2025-06-16T14:00:00"),
    status: "pendente",
    customerType: "mirim",
    professional: "Dr. Carlos Mendes",
    serviceType: "Vacinação para criança e adulto",
    notes: "Nova paciente. Realizar avaliação completa.",
  },
  {
    id: "3",
    customerName: "Robert Johnson",
    customerId: "3",
    age: 42,
    phone: "(+55) 99876-5432",
    dateTime: new Date("2025-06-14T09:15:00"),
    status: "finalizado",
    customerType: "familiar",
    professional: "Dra. Mariana Costa",
    serviceType: "Atendimento nutricional",
    notes: "Acompanhamento pós-tratamento.",
  },
  {
    id: "4",
    customerName: "Emily Davis",
    customerId: "4",
    age: 31,
    phone: "(+55) 97654-3210",
    dateTime: new Date("2025-06-17T16:45:00"),
    status: "cacelado",
    customerType: "adulto",
    professional: "Dr. Paulo Ribeiro",
    serviceType: "Atendimento voltado para diabéticos",
    notes: "Paciente cancelou devido ao compromisso de trabalho.",
  },
  {
    id: "5",
    customerName: "Michael Wilson",
    customerId: "5",
    age: 45,
    phone: "(+55) 95555-4444",
    dateTime: new Date("2025-06-15T13:30:00"),
    status: "confirmado",
    customerType: "familiar",
    professional: "Dra. Ana Silva",
    serviceType: "Acupuntura",
    notes: "Consulta para toda a família. Preparar sala maior.",
  },
  {
    id: "6",
    customerName: "Sarah Brown",
    customerId: "6",
    age: 29,
    phone: "(+55) 94444-3333",
    dateTime: new Date("2025-06-18T11:00:00"),
    status: "pendente",
    customerType: "mirim",
    professional: "Dr. Carlos Mendes",
    serviceType: "Fisioterapia para sequela do COVID",
    notes: "Criança sem o olfato. Priorizar atendimento.",
  },
  {
    id: "7",
    customerName: "David Miller",
    customerId: "7",
    age: 38,
    phone: "(+55) 93333-2222",
    dateTime: new Date("2025-06-14T15:30:00"),
    status: "finalizado",
    customerType: "adulto",
    professional: "Dra. Mariana Costa",
    serviceType: "Tratamento odontológico",
    notes: "Paciente satisfeito com o atendimento.",
  },
  {
    id: "8",
    customerName: "Jennifer Taylor",
    customerId: "8",
    age: 33,
    phone: "(+55) 92222-1111",
    dateTime: new Date("2025-06-16T10:00:00"),
    status: "confirmado",
    customerType: "adulto",
    professional: "Dr. Paulo Ribeiro",
    serviceType: "Atendimento Psiquiátrico",
    notes: "Paciente com indícios de depressão.",
  },
  {
    id: "9",
    customerName: "Thomas Anderson",
    customerId: "9",
    age: 41,
    phone: "(+55) 91111-0000",
    dateTime: new Date("2025-06-17T09:30:00"),
    status: "cacelado",
    customerType: "familiar",
    professional: "Dra. Ana Silva",
    serviceType: "Orientações jurídicas",
    notes: "Paciente solicitou reagendamento para a próxima semana.",
  },
  {
    id: "10",
    customerName: "Lisa White",
    customerId: "10",
    age: 27,
    phone: "(+55) 90000-9999",
    dateTime: new Date("2025-06-18T14:15:00"),
    status: "pendente",
    customerType: "mirim",
    professional: "Dr. Carlos Mendes",
    serviceType: "Atendimento psquiátrico",
    notes: "Verificar resultados de exames anteriores.",
  },
  {
    id: "11",
    customerName: "Ricardo Oliveira",
    customerId: "11",
    age: 39,
    phone: "(+55) 99999-8888",
    dateTime: new Date("2025-06-19T11:30:00"),
    status: "confirmado",
    customerType: "adulto",
    professional: "Dra. Mariana Costa",
    serviceType: "Tratamento odontológico",
    notes: "Paciente com histórico de diabetes.",
  },
  {
    id: "12",
    customerName: "Camila Santos",
    customerId: "12",
    age: 25,
    phone: "(+55) 98888-7777",
    dateTime: new Date("2025-06-19T15:00:00"),
    status: "pendente",
    customerType: "adulto",
    professional: "Dr. Paulo Ribeiro",
    serviceType: "Preventivo para mulher",
    notes: "Nova paciente. Verificar histórico familiar.",
  },
  {
    id: "13",
    customerName: "Fernando Almeida",
    customerId: "13",
    age: 52,
    phone: "(+55) 97777-6666",
    dateTime: new Date("2025-06-20T09:00:00"),
    status: "confirmado",
    customerType: "familiar",
    professional: "Dra. Ana Silva",
    serviceType: "Atendimento nutricional",
    notes: "Paciente de longa data. Verificar pressão arterial.",
  },
  {
    id: "14",
    customerName: "Beatriz Lima",
    customerId: "14",
    age: 31,
    phone: "(+55) 96666-5555",
    dateTime: new Date("2025-06-20T14:30:00"),
    status: "pendente",
    customerType: "adulto",
    professional: "Dr. Carlos Mendes",
    serviceType: "Fisioterapia para sequela do COVID",
    notes: "Encaminhada por outro profissional.",
  },
  {
    id: "15",
    customerName: "Gabriel Costa",
    customerId: "15",
    age: 19,
    phone: "(+55) 95555-4444",
    dateTime: new Date("2025-06-21T10:15:00"),
    status: "confirmado",
    customerType: "mirim",
    professional: "Dra. Mariana Costa",
    serviceType: "Atendimento voltado para diabéticos",
    notes: "Paciente em tratamento contínuo.",
  },
];
